### ISSUE TITLE
Yaml repeated nodes are not serialized correctly

### ISSUE THREAD

**Issue by jsight** [goccy/go-yaml#169]
Example template:

```yaml
spec:
  importantthing_one: &importantthing_one some stuff goes here
  otherstuff:
    foobar: *importantthing_one
```

I'd expect the output to match the input. In reality this is the output:
```yaml
 1 | spec:
 2 |   importantthing_one: &importantthing_onesome stuff goes here
 3 |   otherstuff:
 4 |     foobar: *importantthing_one
```

The space between the var name and the content has disappeared.
