### ISSUE TITLE
[Question] `<<` within string causes panic

### ISSUE THREAD

**Issue by gmemstr** [goccy/go-yaml#184]
Doing some experimenting, and it appears that `<<` tokens are being parsed even when they're within an unquoted string, resulting in `panic: runtime error: invalid memory address or nil pointer dereference`.

I can reproduce this with the following YAML file (a minimal CircleCI configuration):

```yaml
version: 2.1

jobs:
    test:
        docker:
            - image: cimg/go:stable
        steps:
            - run: echo <<parameters>> # If this is enclosed in `""`, panic does not occour
```

Double quotes aren't totally necessary for these configurations, which means there's a good chance newer configurations leveraging [pipeline parameters](https://circleci.com/docs/2.0/pipeline-variables/) won't be parseable by this library. My question is - is this behavior intentional?
