### ISSUE TITLE
Unable to interact with a field where its name containing a dot character

### ISSUE THREAD

**Issue by nghialv** [goccy/go-yaml#240]
Hi, thank you for your nice library.
We are using your lib at our OSS https://github.com/pipe-cd/pipe and it works really nice.

As the title of this issue, we are facing a problem while parsing the path `$.data.envoy-config.yaml` because it is containing a dot character. In Kubernetes context, it is normal to specify a field with a file name including its extension so the `.` will be included.
It makes `go-yaml` parses the path in a wrong way.

``` yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy
data:
  envoy-config.yaml: |-
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9095
```

So do we have any way to deal with this case?

Thank you.
