### ISSUE TITLE
yaml.Marshal gets confused with anchors and aliases

### ISSUE THREAD

**Issue by SuperSandro2000** [goccy/go-yaml#259]
I achieved to generate the following yaml output which is not valid because an object cannot be an anchor and alias (with the same name). At least this is a bug and the library should error when it is tried.

```yaml
base_size: 6TB
region: 1
zones:
  id: 1
  nodes:
  - ip_port: 10.114.1.202:6001
    disk: &disk
      count: 3
      size: 6TB
      weight: 0
  - ip_port: 10.114.1.202:6001
    disk: &disk *disk
  - ip_port: 10.114.1.202:6001
    disk: &disk *disk

```

I hopefully copied all relevant go snippets from my code to explain the above because I am not sure what is happening or what I am doing wrong.

What I am trying to achieve is the following valid yaml. The first occurrence of a pointer should be the anchor and the following the aliases.

```yaml
base_size: 6TB
region: 1
zones:
  id: 1
  nodes:
  - ip_port: 10.114.1.202:6001
    disk: &disk
      count: 3
      size: 6TB
      weight: 0
  - ip_port: 10.114.1.202:6001
    disk: *disk
  - ip_port: 10.114.1.202:6001
    disk: *disk
```

```go
type Disk struct {
	Count  uint64
	Size   string
	Weight uint64
}

type Node struct {
	IPPort string   `yaml:"ip_port"`
	Disks  *Disk    `yaml:"disk,anchor"`
}

type Zone struct {
	ID    uint
	Nodes []Node
}

type DiskRules struct {
	BaseSize string `yaml:"base_size"`
	Region   int
	Zones    Zone
}

diskRules := DiskRules{BaseSize: "6TB", Region: 1, Zones: Zone{ID: 1, Nodes: []Node{}}}
disk := Disk{Count: 3, Size: diskRules.BaseSize}
diskRules.Zones.Nodes = []Node{
{IPPort: "10.114.1.202:6001", Disks: &disk},
{IPPort: "10.114.1.202:6001", Disks: &disk},
{IPPort: "10.114.1.202:6001", Disks: &disk},
}

dataYAML, _ := yaml.Marshal(diskRules)
_ := os.WriteFile("tmp", dataYAML, 0644)
```
