### ISSUE TITLE
Nested `BytesUnmarshaler` requires manual indentation

### ISSUE THREAD

**Issue by chanced** [goccy/go-yaml#268]
I have a type that wraps an interface, defined as:

```go
// SchemaItems represents either a *Schema or a slice of *Schemas
//
// In JSON Schema 2020, it would be a single *Schema
type SchemaItems interface {
	IsSlice() bool
	IsBool() bool
	Schema() *Schema
	Schemas() Schemas
}

// SchemaItemsWrapper wraps SchemaItems
type SchemaItemsWrapper struct {
	SchemaItems
}

// MarshalJSON marshals si into json
func (si *SchemaItemsWrapper) MarshalJSON() ([]byte, error) {
	if si == nil || si.SchemaItems == nil {
		return []byte{}, nil
	}
	return json.Marshal(si.SchemaItems)
}

// MarshalYAML marshals si into yaml
func (si *SchemaItemsWrapper) MarshalYAML() ([]byte, error) {
	if si == nil || si.SchemaItems == nil {
		return []byte{}, nil
	}
	return yaml.Marshal(si.SchemaItems)}
```

which produces:

### json
```json
{
  "$id": "https://example.com/tree",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$dynamicAnchor": "node",
  "type": "object",
  "properties": {
    "children": {
      "type": "array",
      "items": {
        "$dynamicRef": "#node"
      }
    },
    "data": true
  }
}
```
### yaml
```yaml
$id: https://example.com/tree
$schema: https://json-schema.org/draft/2020-12/schema
$dynamicAnchor: node
type: object
properties:
  children:
    type: array
    items: null
    $dynamicRef: "#node"
  data: true
```

If I manually prepend `"  "` to the return, it comes out properly:

```go
// MarshalYAML marshals si into yaml
func (si *SchemaItemsWrapper) MarshalYAML() ([]byte, error) {
	if si == nil || si.SchemaItems == nil {
		return []byte{}, nil
	}
	b, err := yaml.Marshal(si.SchemaItems)
	if err != nil {
		return nil, err
	}
	return append([]byte("  "), b...), err
}
```

```yaml
$id: https://example.com/tree
$schema: https://json-schema.org/draft/2020-12/schema
$dynamicAnchor: node
type: object
properties:
  children:
    type: array
    items:
      $dynamicRef: "#node"
  data: true
```
