### ISSUE TITLE
Can't update YAML keeping newlines

### ISSUE THREAD

**Issue by suzuki-shunsuke** [goccy/go-yaml#285]
Thank you for your great project and sorry for bothering you.
I have a question about the usage of this library.

I would like to update a YAML file keeping comments, indents, and new lines.
It succeeded to update a YAML file keeping comments and indents, but new lines were removed.

go.mod

<details>

```
module foo

go 1.17

require github.com/goccy/go-yaml v1.9.5

require (
	github.com/fatih/color v1.10.0 // indirect
	github.com/mattn/go-colorable v0.1.8 // indirect
	github.com/mattn/go-isatty v0.0.12 // indirect
	golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae // indirect
	golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1 // indirect
)
```

</details>

main.go

https://go.dev/play/p/SsSu3_TyYeK

I found `*ast.File.String()` doesn't keep new lines.

https://go.dev/play/p/dT9pQ52wTrD

Expected Result

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v1.3.0 # renovate: depName=aquaproj/aqua-registry

packages:
  - name: suzuki-shunsuke/tfcmt@v3.0.1
```

Actual Result

```yaml
---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
  - type: standard
    ref: v1.3.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: suzuki-shunsuke/tfcmt@v3.0.1
```

I'll really appreciate it if you have any advice.
Thank you.
