### ISSUE TITLE
Inconsistencies node types between empty/single/multiple yaml maps

### ISSUE THREAD

**Issue by nervo** [goccy/go-yaml#310]
When parsing yaml maps, node types are either `ast.MappingNode` or `ast.MappingValueNode`, depending on the number of items it contains:

```yaml
empty: {}  # -> ast.MappingNode
single:  # -> ast.MappingValueNode
    foo: bar
multiple:  # -> ast.MappingNode
    foo: bar
    bar: baz
```

This leads to boring work arounds when trying to walk accross node tree :)

See this playground: https://go.dev/play/p/BezK6udVSfi

**Comment by st3fan** [comment]
And one more case, but it is probably the same root cause:

```
name: Something
jobs:
  deploy:
    name: Deploy
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: superfly/flyctl-actions/setup-flyctl@v1.4
      - run: flyctl deploy --config fly-staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

For the `steps` this gives me:

```
Step 0 is a *ast.MappingValueNode
Step 1 is a *ast.MappingValueNode
Step 2 is a *ast.MappingNode
```

The problem here clearly are single key/value items.  I don't understand Yaml fully and there are probably some ambiguities in it but I wonder if there actually is a case for a `MappingValueNode`  to ever appear without a `MappingNode` as a parent node.
