### ISSUE TITLE
Comments  of the first item of a multiple maps is associated to the map itself

### ISSUE THREAD

**Issue by nervo** [goccy/go-yaml#311]
In case of a map with multiple items, the first item comments are associated to the map node itself.
Single maps items, or other multiple maps items comments are not affected.

Here, in a single item map, `foo` node is a single `ast.MappingValueNode` and correctly get its comments:
```yaml
map_single:
    # foo single comment
    foo: bar
```

In this multiple items maps, `map` node is a `ast.MappingNode`, and get the comments of its first item. This first item comments are therefore empty, whereas the second item comments are correctly set:
```yaml
map_multiple:
    # foo multiple comment
    foo: bar
    # bar multiple comment
    bar: baz
```

See this playground: https://go.dev/play/p/HpPFOrJkVwF

(this could be more or less related to https://github.com/goccy/go-yaml/issues/310)
