### ISSUE TITLE
go-yaml does not properly set indent for nodes obtained from in-line JSON

### ISSUE THREAD

**Issue by efd6** [goccy/go-yaml#324]
The following program shows that nodes derived from in-line JSON do not properly set their indent, resulting in corrupted output.

https://play.golang.com/p/jxYRN0uVB9J

This returns the following output:
```
processors:
  - date:
      if: "ctx.event?.timezone == null && ctx._temp_?.raw_date != null"
      target_field: "@timestamp"
      on_failure:
    ppend":
    eld": "error.message", "value": "{{{ _ingest.on_failure_message }}}"}}]
```

Note that the data is correctly deserialised as can be seen when the data is passed through an `any` and re-serialised, https://play.golang.com/p/6cCkHpw2MYr.
