### ISSUE TITLE
<< : [*default, *stickyness] can't parse correnttly

### ISSUE THREAD

**Issue by yxxhero** [goccy/go-yaml#340]
```yaml
# The default ingress annotations
.x-default: &default
  nginx.ingress.kubernetes.io/auth-url: https://{{ .Values.authService }}
  nginx.ingress.kubernetes.io/auth-response-headers: Authorization
  acme.cert-manager.io/http01-edit-in-place: "true"
  nginx.ingress.kubernetes.io/ssl-redirect: "true"
  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  cert-manager.io/cluster-issuer: letsencrypt-prod

# Additional "soft" stickyness for performance improvements whenever local session caching is involved 
.x-stickyness: &stickyness
  nginx.ingress.kubernetes.io/affinity: cookie
  nginx.ingress.kubernetes.io/affinity-mode: balanced
  nginx.ingress.kubernetes.io/session-cookie-name: _sticky_session
  nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "true"
  
# Proxy caching can be used for caching static content in nginx
.x-proxy-caching: &caching
  nginx.ingress.kubernetes.io/proxy-buffering: "on"
  
###
# Ingress Annotation Templates
###

ingressAnnotations:
  default:
    << : *default
  caching:
    << : [*default, *caching]
  sticky:
    << : [*default, *stickyness]
```

**Comment by yxxhero** [comment]
@goccy could you give me a favor?

**Comment by goccy** [comment]
I did not understand that multiple values can be used for merge key.
So, the bug needs to be fixed.

**Comment by yxxhero** [comment]
@goccy Thanks for your reply.

**Comment by becalmrobin** [comment]
Some pointers about the yaml merge key feature:
There only exists a spec draft for merge keys: https://yaml.org/type/merge.html

The relevant language about sequences:
"If the value associated with the merge key is a sequence, then this sequence is expected to contain mapping nodes and each of these nodes is merged in turn according to its order in the sequence. Keys in mapping nodes earlier in the sequence override keys specified in later mapping nodes."

I have found that you already use the example yaml from the spec draft in your parser tests: https://github.com/goccy/go-yaml/blob/0640a158e99023787bc503fd4476e472d804c3a3/parser/parser_test.go#L305-L330

However in decode_test.go you only test for a subset of the spec draft, and don't use the spec draft example yaml:
https://github.com/goccy/go-yaml/blob/0640a158e99023787bc503fd4476e472d804c3a3/decode_test.go#L1323-L1332

**Comment by vpmv** [comment]
@goccy I'm afraid I have to reopen this issue, since this functionality seems to have regressed. The package is throwing an `UnexpectedNodeTypeError` ("sequence was used where mapping is expected").

Yaml:

```yaml
# defaults.yaml
credentials: &credentials
  username: user
  password: secret

connection: &connection
  host: localhost
  port: 80
  ssl: false

# env.yaml
app:
  <<: *connection
  port: 8080

database:
  <<: [*connection, *credentials]
  host: postgres
  port: 5432
  password: verysecret
```

Error:
```
[8:7] sequence was used where mapping is expected
       5 |   port: 8080
       6 | 
       7 | database:
    >  8 |   <<: [*connection, *credentials]
                 ^
```

Note: The package initially also threw a `DuplicateKeyError` on `app.port`, which can only be resolved with `yaml.AllowDuplicateMapKey()`. It seems keys are expanded with disregard of merge mode.
