### ISSUE TITLE
Indention not preserved for multi-line string

### ISSUE THREAD

**Issue by Dasio** [goccy/go-yaml#356]
It was broken by 1.9.5 release, probably this MR https://github.com/goccy/go-yaml/pull/276

```go
func main() {
	in := `args:
  - |
    key:
      nest1: something
      nest2:
        nest2a: b

`
	f, err := parser.ParseBytes([]byte(in), 0)
	if err != nil {
		panic(err)
	}
	_, err = os.Stdout.Write([]byte(f.String()))
	if err != nil {
		panic(err)
	}
}
```
Output:
```
args:
  - |
    key:
    nest1: something
    nest2:
    nest2a: b
```
Output v1.9.4:
```
args:
  - |
        key:
          nest1: something
          nest2:
            nest2a:
```

Expected:
```
args:
  - |
    key:
      nest1: something
      nest2:
        nest2a: b
```
