### ISSUE TITLE
Need Help with Advanced Custom Serialization

### ISSUE THREAD

**Issue by cpunion** [goccy/go-yaml#410]
Hello,

I'm working with a data structure, which is intended to be flexible and may represent various user-defined structures. Here's an example structure:

```go
type A struct {
  X, Y int
  Dependent *A // maybe other types
  Children []*A // maybe other types
}

a := &A{
  id: 1,
  X: 1,
  Y: 2,
}

b := &A{
  id: 2,
  X: 3,
  Y: 4,
}

c := &A{
  id: 3,
  X: 5,
  Y: 6,
  Children: []*A{
    a,
  },
  Dependent: &A{
    id: 4,
    X: 7,
    Y: 8,
    Dependent: &A{
      id: 5,
      X: 9,
      Y: 10,
    },
  },
}
```

I need to serialize this tree structure in a flattened structure, all references to objects only store their type/id. For example:

```yaml
- type: A
  id: 3
  X: 5
  Y: 6
  Children:
    - type: A
      id: 1
  Dependent:
    type: A
    id: 4
- type: A
  id: 4
  X: 7
  Y: 8
  Dependent:
    type: A
    id: 5
- type: A
  id: 5
  X: 9
  Y: 10
- type: A
  id: 1
  X: 1
  Y: 2
- type: A
  id: 2
  X: 3
  Y: 4
```

I have been using the `CustomMarshaler`. My goal is to serialize the first-level objects normally, but for nested objects, return only type/id and queue them for delayed serialization. The challenge is to determine within the CustomMarshaler when an object is at the first level (i.e., the initial call of `MarshalWithOptions` to our CustomMarshaler) to serialize its simple fields (not sure how to accomplish this), while returning type/id for referenced fields.

Could anyone provide insights or approaches for handling this situation? Any help on how to effectively implement this type of serialization in Go would be greatly appreciated.

Thank you!
