### ISSUE TITLE
Question: Polymorphism

### ISSUE THREAD

**Issue by phhoef** [goccy/go-yaml#416]
I am quite new to Go, so please be patient 😄 

I am trying to unmarshal a quite complex yaml file. I made a smaller example to show what I want to achieve.
The yml has a property of array which holds the same base type, but has different subtypes.
Something like this:
```yaml
mapping:
    - type: http
      name: mapping1
      url: http://blabla.com
      headers:
        - Content-Type: application/json
      body: very long text
    
    - type: gRPC
      name: mapping2
      endpoint: endpoint.com
      auth:
        user: admin
        password: admin 
```

I would like to unmarshal the yaml into structs. Therefore I've built the following structs
```go
type BaseMapping struct {
    mapType string `yaml:"map_type"`
    name string `yaml:"name"`
}

type HttpMapping struct {
    url string `yaml:"url"`
    headers map[string]string `yaml:"headers"`
    body string `yaml:"body"`
}

type GRPCMapping struct {
    endpoint string `yaml:"endpoint"`
    auth Auth `yaml:"auth"`
}

type Auth struct {
    user string `yaml:"user"`
    password string `yaml:"password"`
}
```

It's not clear to me how I can I do that?
I found a few posts ([this](https://alexkappa.medium.com/json-polymorphism-in-go-4cade1e58ed1) for example) for json that are saying I've to write a custom `unmarshalYAML` function with receiver `BaseMapping`.
But as far as I can tell, it's a different library. Is it working the same way with `go-yaml`?

Could someone please give me some guidance?
