### ISSUE TITLE
Unwanted int to float conversion

### ISSUE THREAD

**Issue by xsilas** [goccy/go-yaml#427]
**Describe the bug**
Using the Marshal function on a interface{} converts an integer to a float value despite the gopkg yamlv3 (gopkg.in/yaml.v3) does not:

Port somehow turns into a float:

```yaml
- docker:
    file: Dockerfile
    platform:
    - arch: amd64
      os: linux
    - arch: arm64
      os: linux
  ingresses:
  - host: www
  name: website
  ports:
  - 8080.0
  resources: {}
  user: "101"
```

**To Reproduce**

```go
yamlv3Bytes, err := yamlv3.Marshal(someInterface)
if err != nil {
return err
}
fmt.Println(string(yamlv3Bytes))

yamlBytes, err := yaml.Marshal(someInterface)
if err != nil {
return err
}
fmt.Println(string(yamlBytes))
```

**Expected behavior**
Port should remain an int like so:

```yaml
- docker:
    file: Dockerfile
    platform:
        - arch: amd64
          os: linux
        - arch: arm64
          os: linux
  ingresses:
    - host: www
  name: website
  ports:
    - 8080
  resources: {}
  user: "101"
```

**Screenshots**
![Bildschirmfoto vom 2024-02-19 11-32-17](https://github.com/goccy/go-yaml/assets/116555276/0f7d9400-7eb9-4028-abf7-aed39e748609)

**Version Variables**
 - Go version: 1.22
 - go-yaml's Version: v1.11.3

**Additional context**
If theres a mistake / missunderstanding on my side please let me know
