### ISSUE TITLE
character '-' as string is interpreted as the beginning of a list

### ISSUE THREAD

**Issue by Diliz** [goccy/go-yaml#472]
**Describe the bug**

When the value of an attribute is "-", what's next of this attribute seems to be rendered as a part of a list, which is not the case.

**To Reproduce**
Use the following yaml:
```yaml
cat: -
dog: -
bark: "woof"
```

Unmarshaling then encoding it will be rendered as:
```yaml
cat:
  - dog:
    - bark: "woof"
```

Here an example: https://go.dev/play/p/4IazOu5k7YA

**Expected behavior**

This should be rendered as:
```yaml
cat: "-"
dog: "-"
bark: "woof"
```

**Version Variables**
 - Go version: 1.22
 - go-yaml's Version: 1.12.0
