### ISSUE TITLE
Allow partial Unmarshal to retain anchors and aliases without resolving them

### ISSUE THREAD

**Issue by kav** [goccy/go-yaml#50]
Taking a look at an issue over in Helm where we need to be able to merge several yaml and various other value formats into a single file but we'd like to retain the anchors and possibly aliases.

My initial thought here is we'd probably prefer to to a partial unmarshal that doesn't resolve anchors and alias so we can detect when we are dealing with a literal vs an anchor/alias.

Use case is here:
https://github.com/helm/helm/issues/6699

**Comment by goccy** [comment]
Hi @kav 
I saw a referenced issue.

I understood that you want to refer to it from `alias` ​​after replacing the value defined in `anchor` with an arbitrary one.

For example, can you solve it with like the following API?

```go

yml := `---
image: &image
  version: 1.0.0
  foo: bar
`
anchorOpt := yaml.UnmarshalAnchor(func(anchorName string, anchorValue interface{}) interface{}{
  // anchorName:  image
  // anchorValue: map[string]interface{}{ "version": "1.0.0", "foo" : "bar" }
  if anchorName == "image" {
    anchorValue["version"] = "2.0.0"
  }
  return anchorValue // returns replaced value
})

dec := yaml.NewDecoder(strings.NewReader(yml), anchorOpt)
var v interface{}
dec.Decode(&v) // use replaced anchor value with UnmarshalAnchor option in decoding
```

or 

```go
yaml.UnmarshalAnchor(func(anchorName string, anchorDoc []byte) interface{}{
  // anchorName: image
  // anchorDoc: []byte("version: 1.0.0\nfoo: bar")
  var v map[string]interface{}{}
  yaml.Unmarshal(anchorDoc, &v)
  if anchorName == "image" {
    v["version"] = "2.0.0"
  }
  return v // returns anchor value
})
```

**Comment by kav** [comment]
There are essentially two tasks happening at once that I think make this more complex. We are combining an arbitrary number of yaml files and command line options, which I'm thinking of as sparse yaml, and then resolving anchors. Using the above might work but I'll need to pseudocode out a bit how the resolution logic should determine the final value.

So let's walkthrough an unreasonably hairy example. Though the "asubchart" use case is exactly the common scenario we run into here:
 I run
`helm --set image.version=3.0.0 -f my-values.yaml`
which gives me my first yaml
```yaml
image:
  version: 3.0.0
```
Given I have 
`my-values.yaml`
```yaml
image:
  version: 2.0.0
  foo: baz
```
and the chart has
`values.yaml`
```yaml
image: &image
  version: 1.0.0
  foo: bar
asubchart:
  image:
    version: *image
```

I'm perhaps incorrectly imagining the easiest solution would be to combine the three yamls without resolving the anchor.

`my-values.yaml` + `values.yaml` =
```yaml
image: &image
  version: 2.0.0
  foo: baz
asubchart:
  image:
    version: *image
```
`set` + (`my-values.yaml` + `values.yaml` ) = 
```yaml
image: &image
  version: 3.0.0
  foo: baz
asubchart:
  image:
    version: *image
```
resolve( `set` + (`my-values.yaml` + `values.yaml` )) = 
```yaml
image:
  version: 3.0.0
  foo: baz
asubchart:
  image:
    version: 3.0.0
    foo: baz
```

Using the above proposed api I could perhaps do
```
yaml.UnmarshalAnchor(func(anchorName string, anchorDoc []byte) interface{}{
  // anchorName: image
  // anchorDoc: []byte("version: 1.0.0\nfoo: bar")
  var v map[string]interface{}{}
  yaml.Unmarshal(anchorDoc, &v)
  if anchorName == "image" {
    v["version"] = "2.0.0"
  }
  return v // returns anchor value
})
