### ISSUE TITLE
go-yaml unmarshal string prefix with "- --" to object which cause error yaml file

### ISSUE THREAD

**Issue by buptgarden** [goccy/go-yaml#655]
**Describe the bug**
when I have a argocd Application Yaml, which have a helm parameter like this:
```
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: xxx
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/update-strategy: latest
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: example
    targetRevision: 0.*.*
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: imageRegistry
          value: example
        - name: admission.additional_args
          value: "- --webhook-label-selectors=xxxx"
```

then when you unmarshal and marshal this yaml , the value will become:

```   
value: - --webhook-label-selectors=xxxx
```

there will be a format error with the value. 
How can I control the change variable type. or this is a bug for this lib ?
**To Reproduce**

the unmarsal and marshal code like this ：
```	
        databytes, err := os.ReadFile("example.yaml")
	if err != nil {
		t.Errorf("ReadFile error: %v", err)
		return
	}
	applicationExample := &applicationv1alpha1.Application{}
	err = goyaml.Unmarshal(databytes, applicationExample)
	if err != nil {
		t.Errorf("Unmarshal error: %v", err)
		return
	}
	// some opreatioin on the yaml
	output, err := goyaml.Marshal(applicationExample)
	if err != nil {
		t.Errorf("Marshal error: %v", err)
		return
	}
	os.WriteFile("example.yaml", output, 0644)
```

**Expected behavior**
i want to output the value as a string quto in "",
``` 
value: "- --webhook-label-selectors=xxxx"
```

**Version Variables**
 - Go version: [e.g. 1.22.6 ]
 - go-yaml's Version: [e.g. v1.15.13]
