### ISSUE TITLE
Add ability to enforce strings to be marshalled in block scalar format

### ISSUE THREAD

**Issue by SCP002** [goccy/go-yaml#702]
**Is your feature request related to a problem? Please describe.**
As it seems, currently this library does not have a simple way to specify how strings in structs should be encoded into bytes, here is example:
```go
package main

import (
	"fmt"
	"github.com/goccy/go-yaml"
)

type Playlist struct {
	HeaderLine    string `yaml:"headerLine"`
	EntryTemplate string `yaml:"entryTemplate"`
}

func main() {
	headerLine := `#EXTM3U url-tvg="https://iptvx.one/epg/epg.xml.gz" tvg-shift=0 deinterlace=1 m3uautoload=1`
	entryLine1 := `#EXTINF:-1 group-title="{{.Categories}}",{{.Name}}`
	entryLine2 := `http://{{.EngineAddr}}/ace/getstream?infohash={{.Infohash}}`

	playlist := Playlist{
		HeaderLine:    headerLine,
		EntryTemplate: entryLine1 + "\n" + entryLine2,
	}
	bytes, err := yaml.MarshalWithOptions(playlist)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(bytes))
}
```
That will produce:
```yaml
headerLine: "#EXTM3U url-tvg=\"https://iptvx.one/epg/epg.xml.gz\" tvg-shift=0 deinterlace=1 m3uautoload=1"
entryTemplate: "#EXTINF:-1 group-title=\"{{.Categories}}\",{{.Name}}\nhttp://{{.EngineAddr}}/ace/getstream?infohash={{.Infohash}}"
```
But I would like to see, for example:
```yaml
headerLine: |
  #EXTM3U url-tvg="https://iptvx.one/epg/epg.xml.gz" tvg-shift=0 deinterlace=1 m3uautoload=1
entryTemplate: |
  #EXTINF:-1 group-title="{{.Categories}}",{{.Name}}
  http://{{.EngineAddr}}/ace/getstream?infohash={{.Infohash}}
```

**Describe the solution you'd like**
Perhaps we could add new tags for struct fields to enforce block scalar notation for strings, such as `blockScalar` and use it with combination of `folded` / `literal` to spectify block scalar type and `clip` / `strip` / `keep` to specify block chomping indicator according to https://yaml-multiline.info.

So we could write:
```go
type Playlist struct {
	HeaderLine    string `yaml:"headerLine,blockScalar,folded,strip"`
	EntryTemplate string `yaml:"entryTemplate,blockScalar,literal,keep"`
}
```
To get:
```yaml
headerLine: >-
  #EXTM3U url-tvg="https://iptvx.one/epg/epg.xml.gz" tvg-shift=0 deinterlace=1 m3uautoload=1
entryTemplate: |+
  #EXTINF:-1 group-title="{{.Categories}}",{{.Name}}
  http://{{.EngineAddr}}/ace/getstream?infohash={{.Infohash}}
```
