### ISSUE TITLE
Feature Request: Make github.com/goccy/go-yaml/internal/format public

### ISSUE THREAD

**Issue by StevenACoffman** [goccy/go-yaml#708]
**Is your feature request related to a problem? Please describe.**
I would like to format YAML using go-yaml as a library but the packages are internal only

**Describe the solution you'd like**
I currently use https://github.com/braydonk/yaml and https://github.com/google/yamlfmt, and they have worked pretty well. I would like to make a command-line tool to use go-yaml instead, but the required packages are internal.

**Describe alternatives you've considered**
I would need to rename internal packages so they would be exported.

**Additional context**
I currently use this `.yamlfmt.yaml`:
```
# yamlfmt is an extensible command-line tool or library to format YAML files.
#
# Get it from: https://github.com/google/yamlfmt/releases
# Config format is here: https://github.com/google/yamlfmt/blob/main/docs/config-file.md
formatter:
  type: basic
  indentless_arrays: true
indent: 2
line_ending: lf
```
And I use this for my `.yamllint.yaml`
```
extends: default
rules:
  braces: disable
  brackets: disable
  colons: enable
  commas: disable
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines: disable
  empty-values: disable
  hyphens: enable
  indentation:
    spaces: 2
    check-multi-line-strings: false
    indent-sequences: false
  key-duplicates: enable
  key-ordering: disable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: enable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: disable
  truthy:
    allowed-values: ['true', 'false', 'on'] # 'on' for GH action trigger
    check-keys: false
```

To format yaml and then verify, I currently run this script:
```
#!/bin/bash

function is_bin_in_path {
  builtin type -P "$1" &> /dev/null
}

export GOBIN="$HOME/go/bin"
export PATH="$GOBIN:$PATH"

! is_bin_in_path yamllint && go install -v github.com/wasilibs/go-yamllint/cmd/yamllint@latest
! is_bin_in_path yamlfmt && go install -v github.com/google/yamlfmt/cmd/yamlfmt@latest
! is_bin_in_path shellcheck && go install github.com/wasilibs/go-shellcheck/cmd/shellcheck@latest

# conf options are equivalent to cli options:
# -formatter indentless_arrays=true,retain_line_breaks=true
yamlfmt \
  -conf .yamlfmt.yaml .

# Verification that formatting matches expectations
# Note that due to the sandboxing of the filesystem when using Wasm, 
# currently only files that descend from the current directory when executing the tool
# are accessible to it, i.e., ../yaml/my.yaml or /separate/root/my.yaml will not be found.
yamllint -c .yamllint.yaml .
```
